language: php

sudo: true

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - LARAVEL_VERSION=5.8.*
    - LARAVEL_VERSION=6.0.*

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - sqlite

before_script:
  - travis_retry composer self-update
  - composer require "illuminate/support:${LARAVEL_VERSION}"
  - composer show laravel/framework
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit --no-coverage
